<?php


namespace app\base;


use yii\web\Controller;

class BaseController extends Controller
{
  public function beforeAction($action)
  {
    $lastPage = \Yii::$app->lastPage->getPage();
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function afterAction($action, $result)
  {
    \Yii::$app->lastPage->setPage();
    return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
  }
}